project: 
  type: website
  output-dir: docs

website:
  title: "Shiwani Sapkota: Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./coding_exercise.html
          - text: "Data Analysis Exercise"
            href: ./dataanalysis_exercise.html
          - text: "Visualization Exercise"
            href: ./visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./tidytuesday_exercise.html
      - text: "Flu Analysis"
        menu:
          - text: "Wrangling"
            href: ./fluanalysis/code/Wrangling.html
          - text: "Exploration"
            href: ./fluanalysis/code/Exploration.html
          - text: "Model Fitting"
            href: ./fluanalysis/code/Fitting.html
          - text: "Model Evaluation"
            href: ./fluanalysis/code/Fitting.html
    right:
      - icon: github 
        href: https://github.com/shiwanisapkota/shiwanisapkota-MADA-portfolio       

format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE


